services:
  db:
    image: postgres:16
    container_name: ourmusic-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ourmusic_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ourmusic-backend
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ourmusic_network
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - azuracast_playlists_folder:/var/azuracast/stations/ourmusic/media/Playlists
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ourmusic-frontend
    env_file:
      - ./frontend/.env
    depends_on:
      backend:
        condition: service_started
    networks:
      - ourmusic_network
    ports:
      - "8080:80"
    restart: always

volumes:
  postgres_data:
  azuracast_playlists_folder:
    external: true

networks:
  ourmusic_network:
    name: ourmusic_network
    driver: bridge
