import { afterEach, describe, expect, it, spyOn } from 'bun:test';
import { logger } from '../lib/logger';

const {
  findArtTrack,
  existingVideos,
  isKeptTrack,
  isYouTubePaused,
  parseArtTrack,
  __resetYouTubePause,
} = await import('./youtubeService');

// The shape of every Art Track description measured on 2026-10-05.
function artTrack(line: string): string {
  return [
    'Provided to YouTube by Domino Recording Co',
    '',
    line,
    '',
    'New Wave',
    '',
    '℗ 1993 Hut Recordings',
    '',
    'Released on: 1993-02-22',
    '',
    'Auto-generated by YouTube.',
  ].join('\n');
}

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json' },
  });
}

afterEach(() => {
  spyOn(globalThis, 'fetch').mockRestore?.();
  __resetYouTubePause();
});

describe('parseArtTrack', () => {
  it('reads the recording a distributor delivered', () => {
    expect(parseArtTrack(artTrack('Dead shark II · Helen · Liz Harris'))).toEqual({
      title: 'Dead shark II',
      artists: ['Helen', 'Liz Harris'],
    });
  });

  it('is not fooled by an uploader writing a dot between title and artist', () => {
    expect(parseArtTrack('Idiot Brother · The Auteurs\nlive at the Forum, 1994')).toBeNull();
    expect(parseArtTrack('Provided to YouTube by me\n\nIdiot Brother · The Auteurs')).toBeNull();
  });
});

describe('isKeptTrack', () => {
  const art = (line: string) => parseArtTrack(artTrack(line))!;

  it.each([
    ['Idiot Brother', 'The Auteurs', 'Idiot Brother · The Auteurs'],
    ['Phantom Of Cinder', 'LAPÊCHE', 'Phantom of Cinder · LAPêCHE'],
    ['Pure Michigan', 'Kiwi jr', 'Pure Michigan · Kiwi jr.'],
    ['Get Lucky', 'Daft Punk feat. Pharrell Williams', 'Get Lucky · Daft Punk · Pharrell Williams'],
    [
      'Shattered (feat. Helena Deland)',
      'Jump Source',
      'Shattered (feat. Helena Deland & Ross Meen) · Jump Source · Helena Deland',
    ],
    ['2nd Thought', 'OMD', '2nd Thought (2003 Digital Remaster) · OMD'],
    ['Everybody Up', 'SKYHIGH, Limmz', 'Everybody Up · SKYHIGH · Limmz'],
    ['Vanishing', 'The Bug / Dis Fig', 'Vanishing · The Bug · Dis Fig'],
  ])('takes « %s » by %s for « %s »', (title, artist, line) => {
    expect(isKeptTrack(art(line), title, artist)).toBe(true);
  });

  it.each([
    ['Locked Out', 'Frozen Warnings', 'Locked Out (Smash The Lock) · Frozen Warnings'],
    ['American', 'Frog', 'Peace Frog · The Doors'],
    ['Fine Afternoon', 'Yea-Ming And The Rumours', 'Cheap Thrill · Yea-Ming and The Rumours'],
    ['Vanishing', 'The Bug', 'Vanishing (Numbness Dub) · The Bug · Dis Fig'],
    ['Come Home', 'James', 'Come Home · James Blake'],
  ])('refuses « %s » by %s for « %s »', (title, artist, line) => {
    expect(isKeptTrack(art(line), title, artist)).toBe(false);
  });
});

describe('findArtTrack', () => {
  it('takes the first Art Track of the kept track in search order, past the clip', async () => {
    const fetchSpy = spyOn(globalThis, 'fetch')
      .mockResolvedValueOnce(
        json({ items: [{ id: { videoId: 'clip' } }, { id: { videoId: 'art' } }] })
      )
      .mockResolvedValueOnce(
        json({
          items: [
            {
              id: 'art',
              snippet: { description: artTrack('Walls Come Tumbling Down · The Style Council') },
            },
            { id: 'clip', snippet: { description: 'Official video' } },
          ],
        })
      );

    expect(await findArtTrack('Walls Come Tumbling Down', 'The Style Council')).toEqual({
      status: 'found',
      value: 'art',
    });
    const search = fetchSpy.mock.calls[0]?.[0];
    expect(search).toBeInstanceOf(URL);
    const params = (search as URL).searchParams;
    expect(params.get('q')).toBe('The Style Council Walls Come Tumbling Down');
    expect(params.get('maxResults')).toBe('15');
  });

  it('answers none when no result is its Art Track, so the search link stays', async () => {
    spyOn(globalThis, 'fetch')
      .mockResolvedValueOnce(json({ items: [{ id: { videoId: 'x' } }] }))
      .mockResolvedValueOnce(
        json({ items: [{ id: 'x', snippet: { description: artTrack('Peace Frog · The Doors') } }] })
      );

    expect(await findArtTrack('American', 'Frog')).toEqual({ status: 'none' });
  });

  it('pauses on the daily quota, fails rather than answering none, and never logs the key', async () => {
    const fetchSpy = spyOn(globalThis, 'fetch').mockResolvedValueOnce(
      json({ error: { errors: [{ reason: 'quotaExceeded' }] } }, 403)
    );
    const info = spyOn(logger, 'info');
    const warn = spyOn(logger, 'warn');

    expect(await findArtTrack('Idiot Brother', 'The Auteurs')).toEqual({ status: 'failed' });
    expect(isYouTubePaused()).toBe(true);
    // Paused: the next song does not call YouTube at all.
    expect(await findArtTrack('Asha', 'Pantha Du Prince')).toEqual({ status: 'failed' });
    expect(fetchSpy).toHaveBeenCalledTimes(1);
    expect(JSON.stringify([info.mock.calls, warn.mock.calls])).not.toContain('test-youtube-key');

    info.mockRestore();
    warn.mockRestore();
  });

  it('keeps the key out of the log when the network fails', async () => {
    spyOn(globalThis, 'fetch').mockRejectedValueOnce(
      new TypeError(
        'fetch failed: https://www.googleapis.com/youtube/v3/search?key=test-youtube-key'
      )
    );
    const warn = spyOn(logger, 'warn');

    expect(await findArtTrack('Asha', 'Pantha Du Prince')).toEqual({ status: 'failed' });
    expect(warn).toHaveBeenCalledTimes(1);
    expect(JSON.stringify(warn.mock.calls)).not.toContain('test-youtube-key');

    warn.mockRestore();
  });
});

describe('existingVideos', () => {
  it('names the stored videos still on YouTube, in one call', async () => {
    const fetchSpy = spyOn(globalThis, 'fetch').mockResolvedValueOnce(
      json({ items: [{ id: 'a' }] })
    );

    expect(await existingVideos(['a', 'gone'])).toEqual(new Set(['a']));
    expect(fetchSpy).toHaveBeenCalledTimes(1);
  });

  it('answers null when YouTube cannot say, so nothing is forgotten', async () => {
    spyOn(globalThis, 'fetch').mockResolvedValueOnce(
      json({ error: { errors: [{ reason: 'backendError' }] } }, 500)
    );

    expect(await existingVideos(['a'])).toBeNull();
  });
});
