import { env } from '../config/env';
import type { Lookup } from '../lib/lookup';
import { logger } from '../lib/logger';
import { artistKey, normalizeArtistName, primaryArtistName } from './artistResolver';

// YouTube Data API v3: search.list draws on its own bucket of 100 calls a day, videos.list on
// the 10,000 units of every other method, one unit for up to 50 ids
// (developers.google.com/youtube/v3/determine_quota_cost).
const API = 'https://www.googleapis.com/youtube/v3';
const TIMEOUT_MS = 5_000;
// The clip often ranks above the Art Track; a page of results costs the same search.
const SEARCH_RESULTS = 15;
export const VIDEOS_PER_CALL = 50;
// Quota resets at midnight Pacific time: an hour's pause is enough to retry without hammering.
const QUOTA_PAUSE_MS = 60 * 60 * 1000;

let pausedUntil = 0;

export function isYouTubeEnabled(): boolean {
  return env.YOUTUBE_API_KEY !== undefined;
}

type Fetched<T> = { status: 'ok'; body: T } | { status: 'failed' };

async function getJson<T>(
  method: 'search' | 'videos',
  params: Record<string, string>
): Promise<Fetched<T>> {
  const key = env.YOUTUBE_API_KEY;
  if (!key || Date.now() < pausedUntil) return { status: 'failed' };

  const url = new URL(`${API}/${method}`);
  for (const [name, value] of Object.entries(params)) url.searchParams.set(name, value);
  url.searchParams.set('key', key);

  let response: Response;
  try {
    response = await fetch(url, { signal: AbortSignal.timeout(TIMEOUT_MS) });
  } catch (err) {
    // The error names the URL, which carries the key: only its kind is logged.
    logger.warn('youtube.network_error', { method, name: (err as Error).name });
    return { status: 'failed' };
  }

  if (!response.ok) {
    const body = (await response.json().catch(() => ({}))) as {
      error?: { errors?: { reason?: string }[] };
    };
    const reason = body.error?.errors?.[0]?.reason ?? 'unknown';
    if (response.status === 403 && /quota|limit/i.test(reason)) {
      pausedUntil = Date.now() + QUOTA_PAUSE_MS;
      logger.info('youtube.quota_reached', { method, reason });
    } else {
      logger.warn('youtube.upstream_error', { method, status: response.status, reason });
    }
    return { status: 'failed' };
  }
  return { status: 'ok', body: (await response.json()) as T };
}

/** Whether the daily quota stopped the calls: the batch stops rather than fail every song. */
export function isYouTubePaused(): boolean {
  return Date.now() < pausedUntil;
}

export function __resetYouTubePause(): void {
  pausedUntil = 0;
}

export interface ArtTrack {
  title: string;
  artists: string[];
}

/**
 * An Art Track: the sound recording YouTube builds from a distributor's delivery, identified by
 * its ISRC and release (support.google.com/youtube/answer/6007071). Its description opens with
 * « Provided to YouTube by », names the recording « Title · Artist · Artist », and ends with
 * « Auto-generated by YouTube. » — a format observed on every Art Track measured, not
 * documented, so anything else is not one.
 */
export function parseArtTrack(description: string): ArtTrack | null {
  if (!/^Provided to YouTube by /m.test(description)) return null;
  if (!/^Auto-generated by YouTube\.\s*$/m.test(description)) return null;
  const line = description.split('\n').find((l) => l.includes(' · '));
  if (!line) return null;
  const [title, ...artists] = line.split(' · ').map((part) => part.trim());
  return title && artists.length > 0 ? { title, artists } : null;
}

// What a title says beside the song: who joins it, and a remaster of the same recording.
const BESIDE_THE_SONG =
  /\s*[([](?:feat\.?|ft\.?|featuring|with)\s[^)\]]*[)\]]|\s*[([][^)\]]*\bremaster(?:ed)?\b[^)\]]*[)\]]|\s+-\s+[^-]*\bremaster(?:ed)?\b.*$/gi;

function comparable(text: string): string {
  return normalizeArtistName(text.replace(BESIDE_THE_SONG, '').replace(/['’ʼ`´]/g, ''));
}

/**
 * Whether an Art Track is the kept track: the same title once who joins it and a remaster are
 * set aside — never a looser match, « Locked Out » is not « Locked Out (Smash The Lock) » — and
 * credits that begin with the kept artist, whose name may hold several (« SKYHIGH, Limmz »
 * credited « SKYHIGH · Limmz »). Measured on 93 kept tracks on 2026-10-05: 60 found, none wrong.
 */
export function isKeptTrack(art: ArtTrack, title: string, artist: string): boolean {
  if (comparable(art.title) !== comparable(title)) return false;
  const kept = artistKey(artist);
  return art.artists.some(
    (_, i) => normalizeArtistName(art.artists.slice(0, i + 1).join(' ')) === kept
  );
}

interface SearchBody {
  items?: { id?: { videoId?: string } }[];
}
interface VideosBody {
  items?: { id?: string; snippet?: { description?: string } }[];
}

/** The video id of the kept track's Art Track: one search, then one videos call for the results. */
export async function findArtTrack(title: string, artist: string): Promise<Lookup<string>> {
  const search = await getJson<SearchBody>('search', {
    part: 'snippet',
    type: 'video',
    videoCategoryId: '10',
    maxResults: String(SEARCH_RESULTS),
    q: `${primaryArtistName(artist)} ${title}`,
  });
  if (search.status === 'failed') return { status: 'failed' };
  const ids = (search.body.items ?? []).flatMap((item) =>
    item.id?.videoId ? [item.id.videoId] : []
  );
  if (ids.length === 0) return { status: 'none' };

  const videos = await getJson<VideosBody>('videos', { part: 'snippet', id: ids.join(',') });
  if (videos.status === 'failed') return { status: 'failed' };
  // In search order: the first matching Art Track is the one YouTube ranks highest.
  const byId = new Map((videos.body.items ?? []).map((video) => [video.id, video]));
  for (const id of ids) {
    const art = parseArtTrack(byId.get(id)?.snippet?.description ?? '');
    if (art && isKeptTrack(art, title, artist)) return { status: 'found', value: id };
  }
  return { status: 'none' };
}

/** The ids still on YouTube among up to 50: what refreshes the stored links. */
export async function existingVideos(ids: readonly string[]): Promise<Set<string> | null> {
  const videos = await getJson<VideosBody>('videos', { part: 'id', id: ids.join(',') });
  if (videos.status === 'failed') return null;
  return new Set((videos.body.items ?? []).flatMap((video) => (video.id ? [video.id] : [])));
}

export function videoUrl(id: string): string {
  return `https://www.youtube.com/watch?v=${encodeURIComponent(id)}`;
}
