services:
  db:
    image: postgres:16
    container_name: ourmusicdb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy_manager_default
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  proxy_manager_default:
    external: true
